config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
]

posts/urls.py
from django.contrib import admin
from django.urls import path, include 
from . import views

app_name = "posts"

urlpatterns = [
    path('', views.home, name="home"),
    path('create', views.create, name = "create"), 
    path('post/<int:id>', views.detail, name="detail"),
    path('update/<int:id>', views.update, name="update"),
    path("delete/<int:id>", views.delete, name="delete"),
]

posts/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=50, verbose_name="제목")
    user = models.CharField(max_length=50, verbose_name="유저")
    region = models.CharField(max_length=50, verbose_name="지역")
    price = models.IntegerField(verbose_name="가격")
    content = models.TextField(verbose_name="컨텐츠")
    created_at = models.DateTimeField(auto_now_add=True) 
    updated_at = models.DateTimeField(auto_now=True)

posts/views.py
from django.shortcuts import redirect, render
from .models import Post

# Create your views here.
def home(request):
    query = request.GET.get('query', None)
    if query: 
        posts = Post.objects.filter(region__contains=query)

    else:
        posts = Post.objects.all()

    print(posts)

    context = {
        "posts":posts
    }
    return render(request, template_name="posts/home.html", context=context)

def create(request):
    if request.method == "POST":
        print(request.POST)
        title = request.POST["title"]
        user = request.POST["user"]
        region = request.POST["region"]
        price = request.POST["price"]
        content = request.POST["content"]

        Post.objects.create(title = title, user=user, region=region, price=price, content=content)

        return redirect("/")

    context = {}

    return render(request, template_name="posts/create.html", context=context)

def detail(request, id):
    post = Post.objects.get(id=id)
    context = {
        "post": post
    }
    return render(request, template_name="posts/detail.html", context=context)

def update(request, id):
    if request.method == "POST":
        title = request.POST["title"]
        user = request.POST["user"]
        region = request.POST["region"]
        price = request.POST["price"]
        content = request.POST["content"]

        Post.objects.filter(id=id).update(title=title, user=user, region=region, price=price, content=content)

        return redirect(f"/post/{id}")

    post = Post.objects.get(id=id)
    context = {
        "post": post
    }
    return render(request, template_name="posts/update.html", context=context)

def delete(request, id):
    if request.method == "POST":
        Post.objects.filter(id=id).delete()
        return redirect("/") 

posts/templates/posts/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>게시글 올리기</title>
</head>
<body>
   <form action="{% url 'posts:create' %}" method="post">
    {% csrf_token %}
        <h2>
            <input type="text" name="title" placeholder="제목">
        </h2>
        <p>
            <input type="text" name="user" placeholder="유저">
            <input type="text" name="region" placeholder="지역">
            <input type="number" name="price" placeholder="가격">
        </p>
        <textarea name="content" id="" cols="30" rows="10"></textarea> 
        
        <div>
            <input type="submit" value="제출">
        </div>
   </form>
   
   <a href="{% url 'posts:home' %}">Home</a>
</body>
</html>

posts/templates/posts/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>상세화면</title>
</head>
<body>
    <article>
        <h2>
            제목 : {{ post.title }}
        </h2>
        <p>
            작성자: {{ post.user }}
            지역: {{post.region}}
        </p>
				<p>
            {{post.price}} 원
        </p>
        <div>
            {{post.content}}
        </div>
    </article>

    <div>
        업데이트 : <a href="{% url 'posts:update' post.id %}">update</a>
        <form action="{% url 'posts:delete' post.id %}" method="post">
            {% csrf_token %}
            <button>삭제</button>
        </form>
    </div>
		<div>
        홈 화면으로 가기: <a href="{% url 'posts:home' %}">Home</a>
    </div>
</body>
</html>

posts/templates/posts/home.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>홈 화면</title>
</head>
<body>
    <form action="{% url 'posts:home' %}">
        <input type="search" name="query" placeholder="동네 이름으로 검색해보세요">
    </form>
    {% for post in posts %}
        <article>
            <h1>
                   {{post.title}}
            </h1>
            <p>
                {{post.region}}
                {{post.user}}
            </p>
            <p>
                {{post.price}} 원
            </p>
            <p>
                {{post.content}}
            </p>
        </article>
    {% endfor %}

    <a href="{% url 'posts:create' %}">생성하기</a>
</body>
</html>

posts/templates/posts/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>게시글 올리기</title>
</head>
<body>
   <form action="{% url 'posts:update' post.id %}" method="post">
    {% csrf_token %}
        <h2>
            <input type="text" name="title" placeholder="제목" value="{{post.title}}">
        </h2>
        <p>
            <input type="text" name="user" placeholder="유저" value="{{post.user}}">
            <input type="text" name="region" placeholder="지역" value="{{post.region}}">
						<input type="number" name="price" placeholder="가격" value="{{post.price}}">
        </p>
        <textarea name="content" id="" cols="30" rows="10">{{post.content}}</textarea> 

        <div>
            <input type="submit" value="제출">
        </div>
   </form>
   <a href="{% url 'posts:home' %}">Home</a>
</body>
</html>  